### ISSUE TITLE
Space preservation when removing html tags in squash.js

### ISSUE THREAD

**Issue by pwalter-ebi** [visual-framework/vf-extensions#6]
When using the squash filter, spacing is not preserved, eg
```
<h1>About us</h1>
<p>EMBL-EBI</p>
```

Results in 
```
About usEMBLEBI
```

**Comment by khawkins98** [comment]
Fix merged. Need to tag a new release on npm

**Comment by khawkins98** [comment]
This is now available. The easiest way to update is probably:

`yarn upgrade-interactive --latest`
